version: '3'

services:
  phplong:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80

  # mysql_db:
  #   image: mysql:5.7.16
  #   command: --default-authentication-plugin=mysql_native_password
  #   # restart: always
  #   tty: true
  #   volumes:
  #     - ./ddl:/docker-entrypoint-initdb.d
  #     - ./data/mysql:/var/lib/mysql
  #     - ./data/log/mysql:/var/log/mysql
  #   ports:
  #     - 3305:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   restart: always
  #   ports:
  #     - 9001:80
  #   environment:
  #     - PMA_ARBITRARY=1

  # mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui